import { LearningConcept } from '../../types/learning';

export const fundamentalConcepts: LearningConcept[] = [
  {
    id: 'fa-01-intro-financial-statements',
    category: 'Fundamental Analysis',
    title: 'The Three Core Financial Statements',
    difficulty: 'Beginner',
    durationMinutes: 8,
    description: 'Understand how the Balance Sheet, Income Statement, and Cash Flow Statement interconnect to reveal a company\'s true financial health.',
    type: 'lesson',
    lessonContent: {
      whatYouWillLearn: 'Master the fundamental purpose of the Income Statement, Balance Sheet, and Cash Flow Statement, and how transactions flow across all three statements.',
      explanation: `Financial analysis starts with the three core financial statements published in annual (10-K) and quarterly (10-Q) SEC filings:

1. The Income Statement (P&L):
Reports financial performance over a specific time horizon (quarter or year). It begins with Gross Revenue (top line), subtracts Cost of Goods Sold (COGS) to calculate Gross Profit, subtracts Operating Expenses (SG&A, R&D, D&A) to arrive at Operating Income (EBIT), and finally deducts interest expenses and corporate taxes to reach Net Income (the bottom line).

2. The Balance Sheet:
A snapshot of financial position at a single point in time governed by the fundamental accounting equation:
Assets = Liabilities + Shareholders' Equity

Assets include Current Assets (cash, accounts receivable, inventory) and Non-Current Assets (PP&E, goodwill, intangibles). Liabilities include Current Liabilities (accounts payable, short-term debt) and Long-Term Obligations (bonds, leases). Shareholders' Equity represents retained earnings and paid-in capital.

3. The Cash Flow Statement (CFS):
Reconciles accrual accounting Net Income with actual cash inflows and outflows across three buckets:
- Operating Cash Flow (CFO): Cash generated by core business operations (Net Income + D&A - working capital increases).
- Investing Cash Flow (CFI): Capital expenditures (CapEx), acquisitions, and asset purchases.
- Financing Cash Flow (CFF): Debt issuance/repayment, equity offerings, dividend distributions, and share buybacks.

How They Link Together:
- Net Income from the Income Statement flows into Retained Earnings on the Balance Sheet.
- Net Income forms the starting line of Operating Cash Flow on the Cash Flow Statement.
- Net Capital Expenditures from CFI increase Net Property, Plant & Equipment on the Balance Sheet.
- Ending cash balance on the CFS directly updates the Cash asset line on the Balance Sheet.`,
      chartType: 'none'
    }
  },
  {
    id: 'fa-02-pe-pb-multiples-quiz',
    category: 'Fundamental Analysis',
    title: 'Valuation Multiples: P/E and P/B Quiz',
    difficulty: 'Beginner',
    durationMinutes: 5,
    description: 'Test your ability to evaluate company valuations using Price-to-Earnings (P/E) and Price-to-Book (P/B) ratios.',
    type: 'quiz',
    quizContent: {
      question: 'Company Alpha trades at a Trailing P/E of 35x with expected annual EPS growth of 30%, while Company Beta trades at a P/E of 12x with expected annual EPS growth of 2%. Why might Company Alpha be considered more attractively valued despite the higher multiple?',
      options: [
        {
          id: 'opt-1',
          text: 'Company Alpha has a PEG (Price/Earnings-to-Growth) ratio of ~1.17, which is significantly cheaper on a growth-adjusted basis than Company Beta\'s PEG of 6.0.',
          isCorrect: true,
          explanation: 'The PEG ratio normalizes P/E by projected earnings growth rate (P/E ÷ Growth Rate). Alpha\'s PEG is 35 / 30 = 1.17, while Beta\'s PEG is 12 / 2 = 6.0. Lower PEG indicates more earnings growth purchased per multiple unit.'
        },
        {
          id: 'opt-2',
          text: 'High P/E stocks are legally required to distribute higher quarterly cash dividends to shareholders.',
          isCorrect: false,
          explanation: 'P/E ratios have no legal relationship to dividend mandates; high P/E growth companies often pay zero dividends to reinvest cash.'
        },
        {
          id: 'opt-3',
          text: 'A P/E above 30x automatically guarantees that the company has no long-term debt liabilities on its balance sheet.',
          isCorrect: false,
          explanation: 'P/E reflects market capitalization divided by net income; it does not measure debt levels or capital structure.'
        },
        {
          id: 'opt-4',
          text: 'Company Beta\'s lower multiple implies that its accounting statements are subject to immediate regulatory audit.',
          isCorrect: false,
          explanation: 'Low P/E multiples generally reflect low growth expectations, cyclicality, or distress, not automatic regulatory investigations.'
        }
      ]
    }
  },
  {
    id: 'fa-03-dcf-valuation',
    category: 'Fundamental Analysis',
    title: 'Discounted Cash Flow (DCF) Valuation',
    difficulty: 'Intermediate',
    durationMinutes: 12,
    description: 'Master the intrinsic valuation methodology used to value businesses based on their projected future cash flows discounted to present value.',
    type: 'lesson',
    lessonContent: {
      whatYouWillLearn: 'Learn how to forecast Unlevered Free Cash Flow (FCFF), calculate Weighted Average Cost of Capital (WACC), and determine Enterprise and Equity Value.',
      explanation: `Discounted Cash Flow (DCF) is the foundation of intrinsic valuation: a company is fundamentally worth the sum of all future cash flows it will produce, discounted back to today at an appropriate risk-adjusted rate.

Step 1: Project Unlevered Free Cash Flow (FCFF)
FCFF represents cash available to all capital providers (debt and equity) after operating expenses and reinvestment needs:
FCFF = EBIT × (1 - Tax Rate) + D&A - Capital Expenditures (CapEx) - Δ Net Working Capital (NWC)

Step 2: Determine the Discount Rate (WACC)
Cash flows are discounted using the Weighted Average Cost of Capital:
WACC = (E/V × Ke) + (D/V × Kd × (1 - Tax Rate))
Where Ke is the Cost of Equity (derived via CAPM: Rf + Beta × Equity Risk Premium), and Kd is the pre-tax Cost of Debt.

Step 3: Estimate Terminal Value (TV)
Since businesses operate indefinitely, Terminal Value captures cash flows beyond the explicit forecast period (typically 5 to 10 years):
- Gordon Growth Model: TV = [FCFF_final × (1 + g)] / (WACC - g), where g is the perpetual long-term GDP growth rate (typically 2-3%).
- Exit Multiple Method: TV = Projected Final Year EBITDA × Industry EV/EBITDA Multiple.

Step 4: Bridge Enterprise Value to Equity Value per Share
1. Sum of Present Value of Discrete FCFFs + Present Value of Terminal Value = Enterprise Value (EV).
2. Equity Value = Enterprise Value - Total Debt - Preferred Stock - Minority Interest + Total Cash & Equivalents.
3. Implied Share Price = Equity Value / Diluted Shares Outstanding.

Key Rule: If Implied Share Price > Current Market Price, the stock offers an intrinsic margin of safety.`,
      chartType: 'none'
    }
  },
  {
    id: 'fa-04-free-cash-flow-quiz',
    category: 'Fundamental Analysis',
    title: 'Free Cash Flow vs. Net Income Quiz',
    difficulty: 'Intermediate',
    durationMinutes: 6,
    description: 'Assess your ability to distinguish between accrual accounting earnings and genuine cash generation.',
    type: 'quiz',
    quizContent: {
      question: 'A rapidly expanding manufacturing enterprise reports $50M in Net Income, yet its Operating Cash Flow is -$15M. Which combination of factors most commonly explains this severe divergence?',
      options: [
        {
          id: 'opt-1',
          text: 'Massive build-up of uncollected accounts receivable and ballooning raw inventory that absorbed more cash than the reported accrual revenue generated.',
          isCorrect: true,
          explanation: 'Under accrual accounting, revenues are booked when earned rather than when cash is collected. Rapidly expanding working capital (uncollected receivables and excess inventory buildup) consumes cash, causing operating cash flow to turn negative despite accounting profits.'
        },
        {
          id: 'opt-2',
          text: 'The company issued new common shares to institutional funds at a premium valuation.',
          isCorrect: false,
          explanation: 'Issuing equity represents a financing cash inflow (CFF) and does not reduce Operating Cash Flow.'
        },
        {
          id: 'opt-3',
          text: 'Depreciation expenses on manufacturing equipment were recognized at twice their standard rate.',
          isCorrect: false,
          explanation: 'Depreciation is a non-cash expense added BACK to Net Income in the Operating Cash Flow calculation; higher D&A would increase cash flow relative to net income.'
        },
        {
          id: 'opt-4',
          text: 'The enterprise repurchased long-term senior corporate bonds on the open secondary market.',
          isCorrect: false,
          explanation: 'Bond repayments are categorized under Financing Cash Flow (CFF), not Operating Cash Flow.'
        }
      ]
    }
  },
  {
    id: 'fa-05-dupont-analysis',
    category: 'Fundamental Analysis',
    title: 'DuPont Analysis: Deconstructing Return on Equity',
    difficulty: 'Intermediate',
    durationMinutes: 10,
    description: 'Break down ROE into Profit Margin, Asset Turnover, and Financial Leverage to pinpoint the true drivers of shareholder profitability.',
    type: 'lesson',
    lessonContent: {
      whatYouWillLearn: 'Understand the 3-step and 5-step DuPont decomposition models to determine whether high ROE stems from pricing power, operational efficiency, or risky debt leverage.',
      explanation: `Return on Equity (ROE = Net Income / Shareholders' Equity) is one of the most widely cited profitability metrics. However, high ROE can be deceiving if it is engineered purely through dangerous debt. DuPont analysis solves this by breaking ROE into three distinct operational drivers:

The 3-Step DuPont Equation:
ROE = Operating Profitability × Operational Efficiency × Financial Leverage
ROE = (Net Income / Revenue) × (Revenue / Total Assets) × (Total Assets / Shareholders' Equity)
ROE = Net Profit Margin × Asset Turnover × Equity Multiplier

1. Net Profit Margin (Net Income / Revenue):
Measures pricing power, product differentiation, and cost control. High margins indicate wide competitive moats (e.g., luxury goods, enterprise SaaS).

2. Asset Turnover (Revenue / Total Assets):
Measures how efficiently management utilizes capital assets to generate sales volume. High turnover is typical of retail and logistics operators (e.g., Costco, Walmart).

3. Equity Multiplier (Total Assets / Shareholders' Equity):
Measures financial leverage. A higher multiplier means assets are funded by liabilities rather than equity capital.

Why DuPont Matters:
- Two companies can both report 20% ROE. Company A achieves it through 15% net margin and 1.3x leverage (sustainable, high-quality).
- Company B achieves it through 2% net margin and 10x leverage (fragile, high bankruptcy risk during economic contractions).`,
      chartType: 'none'
    }
  },
  {
    id: 'fa-06-economic-moats',
    category: 'Fundamental Analysis',
    title: 'Competitive Moats & Sustainable Advantage',
    difficulty: 'Beginner',
    durationMinutes: 9,
    description: 'Learn Warren Buffett\'s qualitative framework for identifying durable competitive advantages that protect high returns on capital.',
    type: 'lesson',
    lessonContent: {
      whatYouWillLearn: 'Identify the five primary structural economic moats: Network Effects, Switching Costs, Cost Advantages, Intangible Assets, and Efficient Scale.',
      explanation: `In economics, supernormal profits attract competition until excess returns are competed away. An "Economic Moat" is a structural barrier that prevents rivals from eroding a firm's profits and market share over decades.

The Five Primary Moat Sources:

1. Network Effects:
The value of a service increases exponentially as more users join.
- Direct: Communication networks, social platforms.
- Indirect/Two-Sided: Payment networks (Visa/Mastercard), operating systems (iOS, Android).

2. High Switching Costs:
When the friction, cost, or operational risk of migrating to a competitor outweighs potential savings.
- Examples: Core ERP software (SAP, Oracle), specialized aircraft engines, laboratory instruments.

3. Cost Advantages:
Structural capabilities that allow a firm to produce goods or services at lower unit costs than any competitor:
- Economies of Scale (logistics density, purchasing power).
- Proprietary low-cost resource extraction or unique location advantage.

4. Intangible Assets:
- Strong Brands: Enable premium pricing without losing volume (Apple, Ferrari).
- Patents & IP: Government-enforced exclusivity (pharmaceuticals, semiconductor designs).
- Regulatory Licenses: Significant barriers to new market entrants (ratings agencies, utilities).

5. Efficient Scale:
When a natural market size is limited and fully served by one or two incumbents. A new entrant would cause excess capacity and destroy profitability for all participants (railroads, pipelines).

Quantitative Proof of a Moat:
A company possessing a true moat consistently generates Return on Invested Capital (ROIC) substantially higher than its Weighted Average Cost of Capital (WACC) across full market cycles.`,
      chartType: 'none'
    }
  },
  {
    id: 'fa-07-working-capital-liquidity',
    category: 'Fundamental Analysis',
    title: 'Working Capital, Liquidity & Solvency Ratios',
    difficulty: 'Intermediate',
    durationMinutes: 10,
    description: 'Evaluate short-term liquidity cushions and long-term solvency obligations to assess bankruptcy and distress risks.',
    type: 'lesson',
    lessonContent: {
      whatYouWillLearn: 'Calculate the Current Ratio, Quick Ratio, Cash Conversion Cycle (CCC), and debt solvency metrics to gauge financial resilience.',
      explanation: `A business can be highly profitable on paper and still go bankrupt if it experiences an acute liquidity shortage. Fundamental investors rigorously analyze liquidity (short-term obligations) and solvency (long-term debt capacity).

1. Short-Term Liquidity Ratios:
- Current Ratio = Current Assets / Current Liabilities (Benchmark: > 1.5x)
- Quick Ratio (Acid Test) = (Cash + Marketable Securities + Accounts Receivable) / Current Liabilities (Excludes illiquid inventory; Benchmark: > 1.0x)
- Cash Ratio = Cash & Equivalents / Current Liabilities

2. The Cash Conversion Cycle (CCC):
Measures the number of days required to convert raw cash invested in operations back into collected cash:
CCC = Days Inventory Outstanding (DIO) + Days Sales Outstanding (DSO) - Days Payable Outstanding (DPO)
- DIO: Average days inventory sits in warehouses before sale.
- DSO: Average days required to collect cash from credit customers.
- DPO: Average days company takes to pay suppliers.
*Negative CCC (e.g., Amazon, Apple) indicates the company is funded by supplier credit interest-free.*

3. Solvency & Debt Health:
- Debt-to-Equity = Total Debt / Total Shareholders' Equity
- Net Debt to EBITDA = (Total Debt - Cash) / EBITDA (Values > 3.5x-4.0x indicate high leverage risk)
- Interest Coverage Ratio = EBIT / Interest Expense (Values < 2.0x indicate severe distress risk in rising rate environments).`,
      chartType: 'none'
    }
  },
  {
    id: 'fa-08-wacc-cost-of-capital-quiz',
    category: 'Fundamental Analysis',
    title: 'WACC & Capital Structure Quiz',
    difficulty: 'Advanced',
    durationMinutes: 7,
    description: 'Test your mastery of corporate cost of capital, capital structure dynamics, and tax shields.',
    type: 'quiz',
    quizContent: {
      question: 'According to modern corporate finance theory and the Capital Asset Pricing Model (CAPM), holding everything else constant, how does an increase in the statutory corporate income tax rate affect a debt-financed firm\'s Weighted Average Cost of Capital (WACC)?',
      options: [
        {
          id: 'opt-1',
          text: 'It decreases WACC because the after-tax cost of debt [Kd × (1 - Tax Rate)] declines due to a larger interest tax shield.',
          isCorrect: true,
          explanation: 'Interest payments on corporate debt are tax-deductible. As the statutory tax rate increases, the value of this interest tax shield expands, reducing the effective after-tax cost of debt capital [Kd × (1 - t)], which drives down the overall blended WACC.'
        },
        {
          id: 'opt-2',
          text: 'It increases WACC because higher corporate taxes increase the firm\'s unlevered asset beta.',
          isCorrect: false,
          explanation: 'Unlevered asset beta reflects underlying business operational risk and is independent of statutory tax rates.'
        },
        {
          id: 'opt-3',
          text: 'It has zero effect on WACC because tax shields are exactly cancelled out by mandatory dividend tax credits under Modigliani-Miller Theorem without taxes.',
          isCorrect: false,
          explanation: 'Under Modigliani-Miller with corporate taxes, interest deductibility creates a positive value tax shield that directly reduces overall WACC.'
        },
        {
          id: 'opt-4',
          text: 'It immediately increases the cost of equity (Ke) by the exact percentage hike in corporate income taxes.',
          isCorrect: false,
          explanation: 'The cost of equity is determined by risk-free rate, beta, and equity risk premium; it does not rise one-for-one with corporate tax rates.'
        }
      ]
    }
  },
  {
    id: 'fa-09-quality-of-earnings-forensics',
    category: 'Fundamental Analysis',
    title: 'Forensic Accounting & Quality of Earnings',
    difficulty: 'Advanced',
    durationMinutes: 14,
    description: 'Detect accounting manipulations, aggressive revenue recognition, capitalized expenses, and low-quality non-GAAP adjustments.',
    type: 'lesson',
    lessonContent: {
      whatYouWillLearn: 'Learn how to detect revenue timing distortions, aggressive expense capitalization, accrual anomalies (Sloan metric), and misleading non-GAAP metrics.',
      explanation: `Reported GAAP and non-GAAP earnings can be legally or illegally managed by executives to meet quarterly consensus estimates. Forensic fundamental analysis evaluates the true "Quality of Earnings."

1. The Accrual Anomaly (Sloan Ratio):
Net Income consists of Cash Flows + Accruals. High accruals predict lower future earnings persistence and subsequent stock underperformance:
Sloan Accruals Ratio = (Net Income - Operating Cash Flow - Investing Cash Flow) / Average Total Assets
*If the accrual ratio exceeds +10%, earnings are heavily reliant on accounting estimates rather than realized cash.*

2. Revenue Recognition Red Flags:
- Channel Stuffing: Pushing unneeded inventory to distributors at quarter-end with lenient return terms.
- Bill-and-Hold Arrangements: Recognizing revenue before shipping goods.
- Divergence: Accounts Receivable growing much faster than Revenue (DSO increasing significantly).

3. Expense Capitalization Tricks:
- Capitalizing routine operational expenses as long-term intangible assets or software development costs (e.g., WorldCom capitalized line costs to avoid recognizing them on the P&L).
- Under-depreciating aging assets by artificially extending useful depreciable asset lives.

4. Non-GAAP & "Adjusted EBITDA" Distortions:
Watch out for management excluding standard, recurring costs such as:
- Stock-Based Compensation (SBC): Real economic dilution to common shareholders.
- Recurring "one-time" restructuring charges year after year.
- Litigation and customer acquisition costs categorized as non-operating items.`,
      chartType: 'none'
    }
  },
  {
    id: 'fa-10-economic-moat-roic-quiz',
    category: 'Fundamental Analysis',
    title: 'ROIC vs. WACC Value Creation Quiz',
    difficulty: 'Advanced',
    durationMinutes: 6,
    description: 'Validate your grasp of corporate value creation, economic value added (EVA), and reinvestment rates.',
    type: 'quiz',
    quizContent: {
      question: 'Company Meridian achieves an average Return on Invested Capital (ROIC) of 7% while its Weighted Average Cost of Capital (WACC) is 10%. Meridian announces a $1B capital expenditure initiative to accelerate annual revenue growth from 4% to 12%. What will be the mathematical impact on Meridian\'s intrinsic shareholder value?',
      options: [
        {
          id: 'opt-1',
          text: 'Intrinsic value will decrease because growing when ROIC < WACC destroys economic value with every dollar of incremental capital invested (negative economic spread).',
          isCorrect: true,
          explanation: 'Economic Value Added (EVA) is defined as Invested Capital × (ROIC - WACC). When ROIC is below WACC, the economic spread is negative (-3%). Accelerating growth in a value-destroying business forces more capital into sub-cost-of-capital projects, destroying shareholder value faster.'
        },
        {
          id: 'opt-2',
          text: 'Intrinsic value will increase proportionally because revenue growth is the sole fundamental driver in DCF modeling.',
          isCorrect: false,
          explanation: 'Growth only creates value when ROIC exceeds the cost of capital (WACC). Growth with negative spread destroys value.'
        },
        {
          id: 'opt-3',
          text: 'Intrinsic value remains completely unchanged because top-line growth exactly balances out financial cost of capital.',
          isCorrect: false,
          explanation: 'Faster unprofitable growth requires more cash investment at negative net present values, systematically reducing equity value.'
        },
        {
          id: 'opt-4',
          text: 'Intrinsic value will increase because capital expenditures create tax-deductible depreciation shields that offset all WACC penalties.',
          isCorrect: false,
          explanation: 'Depreciation tax shields reduce tax liabilities but cannot overcome negative underlying project return spreads.'
        }
      ]
    }
  }
];
