/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "primary-container": "#008090",
        "primary-fixed": "#9eefff",
        "tertiary-container": "#65758c",
        "on-background": "#1a1c1d",
        "on-surface": "#1a1c1d",
        "surface-dim": "#dadadc",
        "on-primary-fixed-variant": "#004e59",
        "secondary-fixed-dim": "#bec6e0",
        "primary-fixed-dim": "#77d4e5",
        "secondary-fixed": "#dae2fd",
        "outline-variant": "#bdc8cb",
        "on-surface-variant": "#3e494b",
        "secondary-container": "#dae2fd",
        "on-primary-container": "#f5fdff",
        "on-error": "#ffffff",
        "surface-container-highest": "#e3e2e4",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fcfbff",
        "surface-tint": "#006876",
        "surface": "#faf9fb",
        "primary": "#006572",
        "on-tertiary-fixed": "#0b1c30",
        "background": "#faf9fb",
        "on-secondary-fixed-variant": "#3f465c",
        "on-secondary-fixed": "#131b2e",
        "tertiary-fixed-dim": "#b7c8e1",
        "tertiary-fixed": "#d3e4fe",
        "on-primary-fixed": "#001f24",
        "inverse-primary": "#77d4e5",
        "surface-container-high": "#e8e8ea",
        "inverse-surface": "#2f3032",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f1f0f2",
        "surface-bright": "#faf9fb",
        "outline": "#6e797b",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-low": "#f4f3f5",
        "surface-variant": "#e3e2e4",
        "error": "#ba1a1a",
        "surface-container": "#eeedef",
        "on-secondary-container": "#5c647a",
        "on-tertiary-fixed-variant": "#38485d",
        "secondary": "#565e74",
        "tertiary": "#4d5c72",
        "on-secondary": "#ffffff",
        "status-positive": "#3C7A5C",
        "status-risk": "#ba1a1a"
      },
      fontFamily: {
        heading: ['Outfit', 'sans-serif'],
        body: ['"Hedvig Letters Sans"', 'sans-serif'],
        mono: ['"Space Grotesk"', 'monospace'],
        'headline-md': ['Outfit', 'sans-serif'],
        'display-lg': ['Outfit', 'sans-serif'],
        'headline-sm': ['Outfit', 'sans-serif'],
        'headline-lg': ['Outfit', 'sans-serif'],
        'headline-lg-mobile': ['Outfit', 'sans-serif'],
        'body-md': ['"Hedvig Letters Sans"', 'sans-serif'],
        'label-md': ['"Hedvig Letters Sans"', 'sans-serif'],
        'body-sm': ['"Hedvig Letters Sans"', 'sans-serif'],
        'body-lg': ['"Hedvig Letters Sans"', 'sans-serif'],
      },
      spacing: {
        "xl": "48px",
        "gutter": "24px",
        "lg": "24px",
        "xs": "4px",
        "md": "16px",
        "base": "4px",
        "margin": "32px",
        "sm": "8px",
        "2xl": "64px"
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
